version: "3"

networks:
  projextX:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.100.0/24

services:
  adminer:
    image: adminer:${ADMINER_VERSION}
    networks:
      projextX:
        ipv4_address: 192.168.100.20
    ports:
      - "${ADMINER_HOST_PORT}:8080"
    restart: always

  db:
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    image: percona:${MYSQL_PERCONA_VERSION}
    networks:
      projextX:
        ipv4_address: 192.168.100.12
    ports:
      - "${MYSQL_HOST_PORT}:3306"
    restart: always
    volumes:
      - "${MYSQL_DATA_DIR}:/var/lib/mysql"

  nginx:
    build:
      context: ./nginx
    container_name: nginx
    depends_on:
      - php
      - db
    networks:
      projextX:
        ipv4_address: 192.168.100.10
    ports:
      - "${NGINX_HOST_PORT}:80"
    volumes:
      - ${APPLICATION}:${WWW_DIR}
    working_dir: ${WWW_DIR}

  php:
    build:
      args:
        PHP_EXT_BCMATH: ${PHP_EXT_BCMATH}
        PHP_EXT_BZ2: ${PHP_EXT_BZ2}
        PHP_EXT_CALENDAR: ${PHP_EXT_CALENDAR}
        PHP_EXT_DBA: ${PHP_EXT_DBA}
        PHP_EXT_DOM: ${PHP_EXT_DOM}
        PHP_EXT_ENCHANT: ${PHP_EXT_ENCHANT}
        PHP_EXT_EXIF: ${PHP_EXT_EXIF}
        PHP_EXT_FILEINFO: ${PHP_EXT_FILEINFO}
        PHP_EXT_GD: ${PHP_EXT_GD}
        PHP_EXT_GETTEXT: ${PHP_EXT_GETTEXT}
        PHP_EXT_GMP: ${PHP_EXT_GMP}
        PHP_EXT_IMAP: ${PHP_EXT_IMAP}
        PHP_EXT_INTERBASE: ${PHP_EXT_INTERBASE}
        PHP_EXT_INTL: ${PHP_EXT_INTL}
        PHP_EXT_LDAP: ${PHP_EXT_LDAP}
        PHP_EXT_MYSQLI: ${PHP_EXT_MYSQLI}
        PHP_EXT_OPCACHE: ${PHP_EXT_OPCACHE}
        PHP_EXT_PCNTL: ${PHP_EXT_PCNTL}
        PHP_EXT_PDO_DBLIB: ${PHP_EXT_PDO_DBLIB}
        PHP_EXT_PDO_FIREBIRD: ${PHP_EXT_PDO_FIREBIRD}
        PHP_EXT_PDO_MYSQL: ${PHP_EXT_PDO_MYSQL}
        PHP_EXT_PDO_ODBC: ${PHP_EXT_PDO_ODBC}
        PHP_EXT_PDO_PGSQL: ${PHP_EXT_PDO_PGSQL}
        PHP_EXT_PGSQL: ${PHP_EXT_PGSQL}
        PHP_EXT_PSPELL: ${PHP_EXT_PSPELL}
        PHP_EXT_RECODE: ${PHP_EXT_RECODE}
        PHP_EXT_SHMOP: ${PHP_EXT_SHMOP}
        PHP_EXT_SNMP: ${PHP_EXT_SNMP}
        PHP_EXT_SOAP: ${PHP_EXT_SOAP}
        PHP_EXT_SOCKETS: ${PHP_EXT_SOCKETS}
        PHP_EXT_SYSCMSG: ${PHP_EXT_SYSCMSG}
        PHP_EXT_SYSVSEM: ${PHP_EXT_SYSVSEM}
        PHP_EXT_SYSVSHM: ${PHP_EXT_SYSVSHM}
        PHP_EXT_TIDY: ${PHP_EXT_TIDY}
        PHP_EXT_WDDX: ${PHP_EXT_WDDX}
        PHP_EXT_XDEBUG: ${PHP_EXT_XDEBUG}
        PHP_EXT_XDEBUG_HOST: ${PHP_EXT_XDEBUG_HOST}
        PHP_EXT_XDEBUG_PORT: ${PHP_EXT_XDEBUG_PORT}
        PHP_EXT_XMLRPC: ${PHP_EXT_XMLRPC}
        PHP_EXT_XSL: ${PHP_EXT_XSL}
        PHP_EXT_ZIP: ${PHP_EXT_ZIP}
      context: ./php/${PHP_VERSION}
    container_name: php${PHP_VERSION}
    networks:
      projextX:
        ipv4_address: 192.168.100.11
    volumes:
      - ${APPLICATION}:${WWW_DIR}
