version: "3"

networks:
  projextX:
    driver: bridge
    ipam:
      config:
        - subnet: ${SUBNET_IPV4}

services:
  adminer:
    container_name: adminer
    image: adminer:${ADMINER_VERSION}
    networks:
      projextX:
        ipv4_address: ${ADMINER_IPV4}
    ports:
      - "${ADMINER_HOST_PORT}:8080"
    restart: always

  percona:
    container_name: percona
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    image: percona:${MYSQL_VERSION}
    networks:
      projextX:
        ipv4_address: "${MYSQL_PERCONA_IPV4}"
    ports:
      - "${MYSQL_HOST_PORT}:3306"
    restart: always
    volumes:
      - "${HOST_DATA_DIR_PATH}/percona:/var/lib/mysql"

  php:
    build:
      args:
        PHP_EXT_BCMATH: ${PHP_EXT_BCMATH}
        PHP_EXT_BZ2: ${PHP_EXT_BZ2}
        PHP_EXT_CALENDAR: ${PHP_EXT_CALENDAR}
        PHP_EXT_DBA: ${PHP_EXT_DBA}
        PHP_EXT_DOM: ${PHP_EXT_DOM}
        PHP_EXT_ENCHANT: ${PHP_EXT_ENCHANT}
        PHP_EXT_EXIF: ${PHP_EXT_EXIF}
        PHP_EXT_FILEINFO: ${PHP_EXT_FILEINFO}
        PHP_EXT_GD: ${PHP_EXT_GD}
        PHP_EXT_GETTEXT: ${PHP_EXT_GETTEXT}
        PHP_EXT_GMP: ${PHP_EXT_GMP}
        PHP_EXT_IMAP: ${PHP_EXT_IMAP}
        PHP_EXT_LDAP: ${PHP_EXT_LDAP}
        PHP_EXT_MYSQLI: ${PHP_EXT_MYSQLI}
        PHP_EXT_OPCACHE: ${PHP_EXT_OPCACHE}
        PHP_EXT_PCNTL: ${PHP_EXT_PCNTL}
        PHP_EXT_PDO_DBLIB: ${PHP_EXT_PDO_DBLIB}
        PHP_EXT_PDO_MYSQL: ${PHP_EXT_PDO_MYSQL}
        PHP_EXT_PDO_ODBC: ${PHP_EXT_PDO_ODBC}
        PHP_EXT_PDO_PGSQL: ${PHP_EXT_PDO_PGSQL}
        PHP_EXT_PGSQL: ${PHP_EXT_PGSQL}
        PHP_EXT_SHMOP: ${PHP_EXT_SHMOP}
        PHP_EXT_SNMP: ${PHP_EXT_SNMP}
        PHP_EXT_SOAP: ${PHP_EXT_SOAP}
        PHP_EXT_SOCKETS: ${PHP_EXT_SOCKETS}
        PHP_EXT_SYSCMSG: ${PHP_EXT_SYSCMSG}
        PHP_EXT_SYSVSEM: ${PHP_EXT_SYSVSEM}
        PHP_EXT_SYSVSHM: ${PHP_EXT_SYSVSHM}
        PHP_EXT_TIDY: ${PHP_EXT_TIDY}
        PHP_EXT_XDEBUG: ${PHP_EXT_XDEBUG}
        PHP_EXT_XDEBUG_HOST: ${PHP_EXT_XDEBUG_HOST}
        PHP_EXT_XDEBUG_PORT: ${PHP_EXT_XDEBUG_PORT}
        PHP_EXT_XMLRPC: ${PHP_EXT_XMLRPC}
        PHP_EXT_XSL: ${PHP_EXT_XSL}
        PHP_EXT_ZIP: ${PHP_EXT_ZIP}
      context: ./services/php/7
    container_name: php
    networks:
      projextX:
        ipv4_address: ${PHP_IPV4}
    volumes:
      - ${HOST_WWW_DIR}:/var/www

  postgres:
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    image: postgres:${POSTGRES_VERSION}
    networks:
      projextX:
        ipv4_address: "${POSTGRES_IPV4}"
    ports:
      - "${POSTGRES_HOST_PORT}:5432"
    restart: always
    volumes:
      - "${HOST_DATA_DIR_PATH}/postgres:/var/lib/postgresql/data"

  nginx:
    build:
      args:
        NGINX_DEFAULT: ${NGINX_DEFAULT}
        NGINX_LARAVEL: ${NGINX_LARAVEL}
        NGINX_SYMFONY: ${NGINX_SYMFONY}
      context: ./services/nginx
    container_name: nginx
    depends_on:
      - php
      - postgres
    networks:
      projextX:
        ipv4_address: ${NGINX_IPV4}
    ports:
      - "${NGINX_HOST_PORT}:80"
    volumes:
      - ${HOST_WWW_DIR}:/var/www
    working_dir: /var/www
