version: "3"

services:
  nginx:
    container_name: nginx
    build:
      context: ./nginx
    volumes:
      - ${APPLICATION}:${WWW_DIR}
      - ./nginx/sites/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - php

  php:
    container_name: php${PHP_VERSION}
    image: php:${PHP_VERSION}-fpm
    volumes:
      - ${APPLICATION}:${WWW_DIR}
