version: "3"

networks:
  projextX:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.100.0/24

services:
  nginx:
    container_name: nginx
    build:
      context: ./nginx
    volumes:
      - ${APPLICATION}:${WWW_DIR}
      - ./nginx/sites/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: ${WWW_DIR}
    ports:
      - "${HOST_PORT}:${CONTAINER_PORT}"
    depends_on:
      - php
    networks:
      projextX:
        ipv4_address: 192.168.100.10

  php:
    container_name: php${PHP_VERSION}
    image: php:${PHP_VERSION}-fpm
    volumes:
      - ${APPLICATION}:${WWW_DIR}
    networks:
      projextX:
        ipv4_address: 192.168.100.11
